knw/knw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('knw1/', include('knw1.urls')),
    path('admin/', admin.site.urls),
]

knw/knw1/urls.py
from django.urls import path

from . import views

app_name = 'knw1'
urlpatterns = [
    path('', views.index, name='index'),

    # /knw1/5 会被重定向到 /knw1/5/
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('new/', views.IndexView.as_view(), name='new_index'),
    path('new/<int:pk>/', views.DetailView.as_view(), name='new_detail')
]

knw/knw1/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    # 自动生成了名为id的列，作为primary_key，
    # id从1开始自增
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    
    # 生成的foreginKey为question_id，自动加上了_id，
    # 使用.get(qeustion_id=1)通过foreginKey查询时，要输入完整的列名，加上id
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text

knw/knw1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question, Choice

from django.template import loader

from django.shortcuts import render, get_object_or_404

from django.http import Http404, HttpResponseRedirect
from django.urls import reverse

from django.views import generic

# Create your views here.
def index(request):
   
    question_list = Question.objects.order_by('-pub_date')
    # output = ', '.join([q.question_text for q in question_list])
    # return HttpResponse(output)

    # 使用template
    # template = loader.get_template('knw1/index.html')
    # context = {
    #     'question_list': question_list
    # }
    # return HttpResponse(
    #     template.render(context, request)
    # )

    context = {
        'question_list': question_list
    }
    return render(request, 'knw1/index.html', context)

    # return HttpResponse('from index of knw1')

def detail(request, question_id):
    
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404('Question does not exist')
    
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'knw1/detail.html', {
        'question': question
    })
        
    # return HttpResponse('deatil -> 问题id：%s' % question_id)


def results(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'knw1/results.html', {
        'question': question
    })

    # return HttpResponse('results -> 问题id：%s' % question_id)

def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'knw1/detail.html', {
            'question': question,
            'error_message': 'invalid choice'
        })

    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(
            reverse('knw1:results', args=(question.id,))
        )

    # return HttpResponse('vote -> 问题id：%s' % question_id)


class IndexView(generic.ListView):
    template_name = 'knw1/index.html'
     

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'knw1:detail'

knw/knw1/templates/knw1/detail.html
<html>
    <head>
        <title>knw1 detail</title>
    </head>
    <body>
        <h3>Question: {{question.question_text}}</h3>
<!--        <ul>-->
        <!-- 在此处写了错误的变量名只是不会显示，不会抛出异常，如question写成了qusetion -->
<!--        {% for choice in question.choice_set.all %}-->
<!--            <li>{{ choice.choice_text }}</li>-->
<!--        {% endfor %}-->
<!--        </ul>-->

        <div>
            {% if error_message %}
            <p style="color: red;">{{ error_message }}</p>
            {% endif %}

            <form action="{% url 'knw1:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="{{ forloop.counter }}" value="{{ choice.id }}" />
                <label for="{{ forloop.counter }}">{{ choice.choice_text }}</label>
            {% endfor %}
                <input type="submit" value="vote" />
            </form>
        </div>
    </body>
</html>

knw/knw1/templates/knw1/index.html
<html>
    <head>
        <title>knw1 index</title>
    </head>
    <body>
        <h3>Question List:</h3>
        {% if question_list %}
            <ul>
                {% for question in question_list %}
                    <li>
                    <div>id: {{ question.id }}</div>
                    <div>text: {{ question.question_text }}</div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>no data!</p>
        {% endif %}
    </body>
</html>

knw/knw1/templates/knw1/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>results</title>
</head>
<body>
    <div>
        <h3>Question: {{ question.question_text }}</h3>
        <div>
            <p>votes:</p>
            <ul>
            {% for choice in question.choice_set.all %}
                <li>
                    {{ choice.choice_text }}: {{ choice.votes }}
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</body>
</html>